CREATE EXTENSION unaccent;

CREATE TYPE USER_ROLE AS ENUM ('USER', 'ADMIN');

CREATE TABLE "users" (
  "id" SERIAL PRIMARY KEY,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "deletedAt" TIMESTAMP,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "password" VARCHAR(255) NOT NULL,
  "role" USER_ROLE NOT NULL DEFAULT 'USER'
);
